// Listes de suggestions pour l'autocomplete. « libellé|mots-clés » : les mots-clés ne
// s'affichent pas, ils servent à la recherche avancée (« réseau » trouve « Technicien réseaux »).
export const SUGGEST = {
  jobs: [
    'Technicien en réseaux et télécommunications|réseau télécom it',
    'Technicien de maintenance informatique|helpdesk support it',
    'Développeur web|code javascript site frontend backend',
    'Développeur mobile|android ios application',
    'Développeur full stack|code web',
    'Analyste programmeur|logiciel code',
    'Administrateur systèmes et réseaux|serveur linux it',
    'Data analyst|données excel statistiques',
    'Graphiste|design logo photoshop',
    'Designer UI/UX|interface maquette figma',
    'Community manager|réseaux sociaux communication marketing',
    'Chargé de communication|média presse',
    'Assistant administratif|secrétariat bureau',
    'Secrétaire de direction|bureau assistante',
    'Comptable|finance compta facture',
    'Assistant comptable|compta finance',
    'Gestionnaire de stock|logistique magasin',
    'Assistant de gestion|administration',
    'Chargé de clientèle|vente service client',
    'Commercial|vente prospection',
    'Conseiller de vente|boutique magasin',
    'Caissier|caisse vente',
    'Agent de microfinance|banque crédit',
    'Banquier|banque finance',
    'Infirmier|santé soins hôpital',
    'Sage-femme|santé maternité',
    'Pharmacien|santé médicaments',
    'Médecin généraliste|santé médecine',
    'Enseignant|école éducation classe',
    'Professeur de mathématiques|école lycée',
    'Formateur|éducation formation',
    'Ingénieur civil|construction chantier bâtiment',
    'Ingénieur électricien|électricité énergie',
    'Technicien électricien|électricité installation',
    'Technicien mécanicien|moteur garage automobile',
    'Conducteur de travaux|chantier bâtiment',
    'Architecte|plan construction',
    'Juriste|droit loi contrat',
    'Avocat stagiaire|droit barreau',
    'Journaliste|presse média rédaction',
    'Traducteur|langues rédaction',
    'Chef de projet|gestion équipe',
    'Responsable des ressources humaines|rh recrutement',
    'Agent logistique|transport stock',
    'Chauffeur|transport conduite',
    'Agronome|agriculture culture champ',
    'Vétérinaire|animaux élevage',
    'Cuisinier|restauration cuisine',
    'Serveur|restauration hôtel',
    'Réceptionniste|hôtel accueil',
    'Stagiaire|stage débutant',
    'Bénévole|association volontaire',
  ],
  skills: [
    'Réseaux LAN / WAN|réseau télécom',
    'Configuration de routeurs Cisco|réseau',
    'Adressage IP et VLAN|réseau',
    'Fibre optique|télécom câblage',
    'Câblage structuré|réseau',
    'Administration Linux|système serveur',
    'Administration Windows Server|système serveur',
    'Microsoft Word|bureautique office',
    'Microsoft Excel|bureautique office tableur',
    'Microsoft PowerPoint|bureautique office présentation',
    'Bureautique|office word excel',
    'JavaScript|code web',
    'HTML et CSS|web site',
    'React|web frontend',
    'Node.js|web backend',
    'Python|code données',
    'PHP et MySQL|web base de données',
    'Java|code',
    'SQL|base de données',
    'Git et GitHub|code versions',
    'Photoshop|design image',
    'Illustrator|design logo',
    'Canva|design',
    'Montage vidéo|vidéo',
    'Gestion de projet|équipe planning',
    'Comptabilité générale|compta finance',
    'Tenue de caisse|vente',
    'Gestion de stock|logistique',
    'Service client|vente accueil',
    'Prospection commerciale|vente',
    'Communication écrite|rédaction',
    'Rédaction administrative|bureau',
    'Travail en équipe|soft',
    'Gestion du temps|soft',
    'Esprit d’initiative|soft',
    'Sens de l’organisation|soft',
    'Résolution de problèmes|soft',
    'Prise de parole en public|soft',
    'Permis de conduire B|conduite',
    'Premiers secours|santé',
  ],
  schools: [
    'Université Marien Ngouabi (UMNG)|brazzaville université',
    'École Nationale Supérieure Polytechnique (ENSP)|brazzaville ingénieur technique informatique réseau',
    'Faculté des Sciences et Techniques (FST)|brazzaville sciences université',
    'Faculté des Sciences Économiques (FSE)|brazzaville économie gestion université',
    'Faculté de Droit|brazzaville droit juridique université',
    'Faculté des Sciences de la Santé (FSSA)|brazzaville santé médecine université',
    'École Normale Supérieure (ENS)|brazzaville éducation pédagogie',
    'Institut Supérieur de Gestion (ISG)|brazzaville gestion commerce',
    'École Nationale d’Administration et de Magistrature (ENAM)|brazzaville administration',
    'Université Denis Sassou Nguesso (UDSN)|kintélé université',
    'École Supérieure de Gestion et d’Administration des Entreprises (ESGAE)|brazzaville gestion commerce',
    'École Paramédicale et Médico-Sociale Jean-Joseph Loukabou|brazzaville santé infirmier',
    'Lycée Technique 1er Mai|brazzaville secondaire technique',
    'Lycée Savorgnan de Brazza|brazzaville secondaire',
    'Lycée Chaminade|brazzaville secondaire',
    'Lycée Victor Augagneur|pointe-noire secondaire',
    'Lycée Technique|secondaire',
    'Collège|secondaire',
  ],
  degrees: [
    'Licence en réseaux et télécommunications|réseau télécom',
    'Licence en informatique de gestion|informatique',
    'Licence en génie logiciel|informatique code',
    'Licence en gestion financière|finance',
    'Licence en comptabilité|compta',
    'Licence en économie|économie',
    'Licence en droit|juridique',
    'Licence en sciences de l’information et de la communication|journalisme',
    'Licence en sciences de l’éducation|éducation',
    'Licence en sciences infirmières|santé',
    'BTS en informatique de gestion|bts informatique',
    'BTS en comptabilité et gestion|bts compta commerce',
    'Baccalauréat série C (mathématiques)|secondaire bac sciences',
    'Baccalauréat série D (sciences)|secondaire bac sciences',
    'Baccalauréat série A (lettres)|secondaire bac lettres',
    'Baccalauréat technique série F (électricité, électronique)|secondaire bac technique',
    'Baccalauréat série G (gestion, commerce)|secondaire bac commerce',
    'BEPC|secondaire collège',
    'Master en informatique|master',
    'Master en gestion de projet|master',
    'Certification Cisco CCNA|réseau certification',
    'Certification Microsoft Office|bureautique certification',
    'Formation en bureautique|certificat',
    'Formation en marketing digital|certificat',
  ],
  companies: [
    'MTN Congo|télécom',
    'Airtel Congo|télécom',
    'Congo Telecom|télécom',
    'BGFIBank Congo|banque',
    'LCB Bank (La Congolaise de Banque)|banque',
    'Ecobank Congo|banque',
    'Crédit du Congo|banque',
    'UBA Congo|banque',
    'MUCODEC|banque microfinance',
    'Brasseries du Congo (Brasco)|brasserie industrie',
    'TotalEnergies EP Congo|énergie pétrole',
    'SNPC (Société Nationale des Pétroles du Congo)|pétrole énergie',
    'E²C (Énergie Électrique du Congo)|électricité',
    'LCDE (La Congolaise des Eaux)|eau',
    'Port Autonome de Pointe-Noire|logistique transport',
    'CHU de Brazzaville|santé hôpital',
    'Hôpital général|santé',
    'École primaire|éducation',
    'Cabinet d’avocats|droit',
    'ONG|association humanitaire',
    'Auto-entrepreneur|indépendant',
  ],
  languages: [
    'Français|langue',
    'Anglais|langue',
    'Lingala|langue congo',
    'Kituba (Munukutuba)|langue congo',
    'Lari|langue congo kikongo',
    'Téké|langue congo',
    'Vili|langue congo',
    'Portugais|langue',
    'Espagnol|langue',
    'Arabe|langue',
    'Allemand|langue',
    'Chinois|langue',
  ],
  hobbies: [
    'Football|sport',
    'Basketball|sport',
    'Course à pied|sport',
    'Natation|sport',
    'Lecture|culture',
    'Musique|culture',
    'Danse|culture',
    'Dessin|art',
    'Photographie|art',
    'Cinéma|culture',
    'Voyages|découverte',
    'Cuisine|maison',
    'Bénévolat|association',
    'Échecs|jeu',
    'Jeux vidéo|jeu',
    'Programmation|code',
    'Écriture|culture',
  ],
};

export const SUGGEST_TITLE = {
  jobs: 'métiers et intitulés de poste',
  skills: 'compétences',
  schools: 'établissements',
  degrees: 'diplômes et formations',
  companies: 'entreprises et organisations',
  languages: 'langues',
  hobbies: 'loisirs',
};
