// Listes de suggestions pour l'autocomplete. « libellé|mots-clés » : les mots-clés ne
// s'affichent pas, ils servent à la recherche avancée (« réseau » trouve « Technicien réseaux »).
export const SUGGEST = {
  jobs: [
    'Technicien en réseaux et télécommunications|réseau télécom it',
    'Technicien de maintenance informatique|helpdesk support it',
    'Développeur web|code javascript site frontend backend',
    'Développeur mobile|android ios application',
    'Développeur full stack|code web',
    'Analyste programmeur|logiciel code',
    'Administrateur systèmes et réseaux|serveur linux it',
    'Data analyst|données excel statistiques',
    'Graphiste|design logo photoshop',
    'Designer UI/UX|interface maquette figma',
    'Community manager|réseaux sociaux communication marketing',
    'Chargé de communication|média presse',
    'Assistant administratif|secrétariat bureau',
    'Secrétaire de direction|bureau assistante',
    'Comptable|finance compta facture',
    'Assistant comptable|compta finance',
    'Gestionnaire de stock|logistique magasin',
    'Assistant de gestion|administration',
    'Chargé de clientèle|vente service client',
    'Commercial|vente prospection',
    'Conseiller de vente|boutique magasin',
    'Caissier|caisse vente',
    'Agent de microfinance|banque crédit',
    'Banquier|banque finance',
    'Infirmier|santé soins hôpital',
    'Sage-femme|santé maternité',
    'Pharmacien|santé médicaments',
    'Médecin généraliste|santé médecine',
    'Enseignant|école éducation classe',
    'Professeur de mathématiques|école lycée',
    'Formateur|éducation formation',
    'Ingénieur civil|construction chantier bâtiment',
    'Ingénieur électricien|électricité énergie',
    'Technicien électricien|électricité installation',
    'Technicien mécanicien|moteur garage automobile',
    'Conducteur de travaux|chantier bâtiment',
    'Architecte|plan construction',
    'Juriste|droit loi contrat',
    'Avocat stagiaire|droit barreau',
    'Journaliste|presse média rédaction',
    'Traducteur|langues rédaction',
    'Chef de projet|gestion équipe',
    'Responsable des ressources humaines|rh recrutement',
    'Agent logistique|transport stock',
    'Chauffeur|transport conduite',
    'Agronome|agriculture culture champ',
    'Vétérinaire|animaux élevage',
    'Cuisinier|restauration cuisine',
    'Serveur|restauration hôtel',
    'Réceptionniste|hôtel accueil',
    'Stagiaire|stage débutant',
    'Bénévole|association volontaire',
  ],
  skills: [
    'Réseaux LAN / WAN|réseau télécom',
    'Configuration de routeurs Cisco|réseau',
    'Adressage IP et VLAN|réseau',
    'Fibre optique|télécom câblage',
    'Câblage structuré|réseau',
    'Administration Linux|système serveur',
    'Administration Windows Server|système serveur',
    'Microsoft Word|bureautique office',
    'Microsoft Excel|bureautique office tableur',
    'Microsoft PowerPoint|bureautique office présentation',
    'Bureautique|office word excel',
    'JavaScript|code web',
    'HTML et CSS|web site',
    'React|web frontend',
    'Node.js|web backend',
    'Python|code données',
    'PHP et MySQL|web base de données',
    'Java|code',
    'SQL|base de données',
    'Git et GitHub|code versions',
    'Photoshop|design image',
    'Illustrator|design logo',
    'Canva|design',
    'Montage vidéo|vidéo',
    'Gestion de projet|équipe planning',
    'Comptabilité générale|compta finance',
    'Tenue de caisse|vente',
    'Gestion de stock|logistique',
    'Service client|vente accueil',
    'Prospection commerciale|vente',
    'Communication écrite|rédaction',
    'Rédaction administrative|bureau',
    'Travail en équipe|soft',
    'Gestion du temps|soft',
    'Esprit d’initiative|soft',
    'Sens de l’organisation|soft',
    'Résolution de problèmes|soft',
    'Prise de parole en public|soft',
    'Permis de conduire B|conduite',
    'Premiers secours|santé',
  ],
  schools: [
    'Université de Kinshasa (UNIKIN)|kinshasa université',
    'Université Pédagogique Nationale (UPN)|kinshasa université',
    'Université Protestante au Congo (UPC)|kinshasa université',
    'Université Catholique du Congo (UCC)|kinshasa université',
    'Université de Lubumbashi (UNILU)|lubumbashi université',
    'Université de Kisangani (UNIKIS)|kisangani université',
    'Université Marien Ngouabi|brazzaville université',
    'Institut Supérieur de Techniques Appliquées (ISTA)|kinshasa informatique technique',
    'Institut Supérieur Pédagogique (ISP)|éducation pédagogie',
    'Institut Supérieur de Commerce (ISC)|kinshasa commerce gestion',
    'Institut Supérieur d’Informatique Programmation et Analyse (ISIPA)|kinshasa informatique',
    'Institut Supérieur des Techniques Médicales (ISTM)|santé médical',
    'Institut Facultaire des Sciences de l’Information et de la Communication (IFASIC)|kinshasa journalisme communication',
    'Institut National du Bâtiment et des Travaux Publics (INBTP)|kinshasa construction',
    'École Supérieure d’Ingénieurs Industriels (ESI)|ingénieur',
    'Lycée Technique|secondaire',
    'Institut Technique Commercial|secondaire commerce',
    'Collège|secondaire',
  ],
  degrees: [
    'Licence en réseaux et télécommunications|ista réseau télécom',
    'Licence en informatique de gestion|ista informatique',
    'Licence en génie logiciel|informatique code',
    'Licence en gestion financière|finance',
    'Licence en comptabilité|compta',
    'Licence en économie|économie',
    'Licence en droit|juridique',
    'Licence en sciences de l’information et de la communication|journalisme',
    'Licence en pédagogie appliquée|éducation',
    'Licence en sciences infirmières|santé',
    'Graduat en informatique|graduat',
    'Graduat en gestion commerciale|graduat commerce',
    'Diplôme d’État|secondaire humanités',
    'Diplôme d’État en électricité|secondaire technique',
    'Diplôme d’État en commerce et gestion|secondaire',
    'Master en informatique|master',
    'Master en gestion de projet|master',
    'Certification Cisco CCNA|réseau certification',
    'Certification Microsoft Office|bureautique certification',
    'Formation en bureautique|certificat',
    'Formation en marketing digital|certificat',
  ],
  companies: [
    'Vodacom Congo|télécom',
    'Airtel Congo|télécom',
    'Orange RDC|télécom',
    'Africell|télécom',
    'Rawbank|banque',
    'Equity BCDC|banque',
    'TMB (Trust Merchant Bank)|banque',
    'Ecobank|banque',
    'Procredit|banque microfinance',
    'Brasimba|brasserie industrie',
    'Bracongo|brasserie industrie',
    'Total Energies|énergie',
    'SNEL|électricité',
    'Regideso|eau',
    'Hôpital général|santé',
    'École primaire|éducation',
    'Cabinet d’avocats|droit',
    'ONG|association humanitaire',
    'Auto-entrepreneur|indépendant',
  ],
  languages: [
    'Français|langue',
    'Anglais|langue',
    'Lingala|langue congo',
    'Swahili|langue congo',
    'Kikongo|langue congo',
    'Tshiluba|langue congo',
    'Portugais|langue',
    'Espagnol|langue',
    'Arabe|langue',
    'Allemand|langue',
    'Chinois|langue',
  ],
  hobbies: [
    'Football|sport',
    'Basketball|sport',
    'Course à pied|sport',
    'Natation|sport',
    'Lecture|culture',
    'Musique|culture',
    'Danse|culture',
    'Dessin|art',
    'Photographie|art',
    'Cinéma|culture',
    'Voyages|découverte',
    'Cuisine|maison',
    'Bénévolat|association',
    'Échecs|jeu',
    'Jeux vidéo|jeu',
    'Programmation|code',
    'Écriture|culture',
  ],
};

export const SUGGEST_TITLE = {
  jobs: 'métiers et intitulés de poste',
  skills: 'compétences',
  schools: 'établissements',
  degrees: 'diplômes et formations',
  companies: 'entreprises et organisations',
  languages: 'langues',
  hobbies: 'loisirs',
};
